

name: parentWorkflow
  


on:
  
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 
  workflow_dispatch:
    inputs:
      branch:  # Optional input to specify the branch (you can customize this as needed)
        description: 'Branch to run the workflow on'
        required: true
    


jobs:

  build:

    runs-on: ubuntu-latest

   
    steps:
    
      - uses: actions/checkout@v3

    
      - name: Run a one-line script
        run: echo Hello, world!

 
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
